# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: Azure Pipelines

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean verify'
    options: '-U -B'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    codeCoverageToolOption: 'JaCoCo'
#    codeCoverageClassFilesDirectories: 'module1/target/classes,module2/target/classes'
#    codeCoverageSourceDirectories: 'module1/src,module2/src'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: CopyFiles@2.209.0
  inputs:
    Contents: 'pom.xml'
    TargetFolder: 'Test'
#- task: PublishCodeCoverageResults@1
#  inputs:
#    codeCoverageTool: 'JaCoCo'
#    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/target/site/jacoco-aggregate/jacoco.xml'
#    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage/target/site/jacoco-aggregate'
- task: CmdLine@2
  inputs:
    script: |
      cd Test
      dir