# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: Azure Pipelines

steps:
#- task: JavaToolInstaller@0
#  inputs:
#    versionSpec: '8'
#    jdkArchitectureOption: 'x64'
#    jdkSourceOption: 'PreInstalled'
- task: InstallSSHKey@0.200.0
  inputs:
    knownHostsEntry: 'ssh-ed25519:AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl'
    sshKeySecureFile: 'id_ras'
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGX0k5D9MAe1GIJILZi5+joAdUYxcoGLZiZpqoSX4AQWFMtYiLIfRuFBV3ov7CBF6UQaJK6I0u3MRJKsQI2/HvHOSj8aB5FjLImt13JiJMOfB0IOWJ1jZOQ2N2UfuHwluekK4gCCvmJZIPrjwRRf8w6BzJmRZoHQD0Nw5BNZbYGBR2o3M85iNOiKYWguXCVekiTsKxvuzX4OvTSjr6mbuxnjDbCOAii2MuRk6PD/MVa4pY1u7yn08ny69by/lFfPwD/9yf5dzwDw1DeWOufkeYCYklZeuNAMuilQ1a/M72FBHTgb/8nZZ+Op8OtvREmmCKu1qml01hc3DlNe5M7r7YOXzpUuY2avdOmJl6RDk7okVx+bbxswfZxpqKdKgTQ/BEHkDMwaDJC7a/39MQYU+xaGpZCUaLSNArkpE8wmAtn/05QOaYUQ569ba6u9YCYR1YttupKchMJDHxyNzi+PYxtS/JrqJlt3tNdFCpuTpIj9p+KrAsyWy5ctLabGvQFAs= roman@n148'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean verify'
    options: '-U -B'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    codeCoverageToolOption: 'JaCoCo'
#    codeCoverageClassFilesDirectories: 'module1/target/classes,module2/target/classes'
#    codeCoverageSourceDirectories: 'module1/src,module2/src'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
#- task: CopyFiles@2.209.0
#  inputs:
#    Contents: 'pom.xml'
#    TargetFolder: 'Test'
#- task: CmdLine@2
#  inputs:
#    script: |
#      dir
#- task: DeleteFiles@1
#  inputs:
#    SourceFolder: 
#    Contents: 'pom.xml'
#- task: CmdLine@2
#  inputs:
#    script: |
#     dir