# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: windows-latest

steps:
  - task: DownloadGithubNpmPackage@1
    inputs:
      packageName: ktsn-npm-package-example
      version: 1.0.1
      externalEndpoints: https://github.com/ktsn/npm-package-example.git
#jobs:
#  - job: macos_test
#    pool:
#        vmImage: macos-latest
#    steps:
#    - script: |
#          gem install cocoapods
#    - task: CocoaPods@0
#      inputs:
#        forceRepoUpdate: false